### ISSUE TITLE
Final Release date?

### ISSUE THREAD

**Issue by felipecp** [SoriUR/mutanus#1]
Hello guys! 
We are looking for a tool to implement Mutation Tests on iOS side in huge project.
Do you guys have any ETA about releasing this library?
Is this already usable?

**Comment by usorokin** [comment]
Hi there,
This project is ready to be used. I've tested it on a several projects.
A couple features a still in progress but you can try it out.
If you need any help, contact me

**Comment by usorokin** [comment]
@felipecp Have you managed to make it work?
